version: '3'
services:
  frontend:
    image: switching-frontend
    ports:
      - '3000-3000'
    networks:
      - mern-app
  backend:
    image: switching-backend
    ports:
      - '5050-5050'
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - '27017-27017'
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
