export const FORMATION_LIST_REQUEST = 'FORMATION_LIST_REQUEST'
export const FORMATION_LIST_SUCCESS = 'FORMATION_LIST_SUCCESS'
export const FORMATION_LIST_FAIL = 'FORMATION_LIST_FAIL'

export const FORMATION_DELETE_REQUEST = 'FORMATION_DELETE_REQUEST'
export const FORMATION_DELETE_SUCCESS = 'FORMATION_DELETE_SUCCESS'
export const FORMATION_DELETE_FAIL = 'FORMATION_DELETE_FAIL'
