export const FORMATION_LIST_REQUEST = 'FORMATION_LIST_REQUEST'
export const FORMATION_LIST_SUCCESS = 'FORMATION_LIST_SUCCESS'
export const FORMATION_LIST_FAIL = 'FORMATION_LIST_FAIL'

export const FORMATION_DETAILS_REQUEST = 'FORMATION_DETAILS_REQUEST'
export const FORMATION_DETAILS_SUCCESS = 'FORMATION_DETAILS_SUCCESS'
export const FORMATION_DETAILS_FAIL = 'FORMATION_DETAILS_FAIL'

export const FORMATION_DELETE_REQUEST = 'FORMATION_DELETE_REQUEST'
export const FORMATION_DELETE_SUCCESS = 'FORMATION_DELETE_SUCCESS'
export const FORMATION_DELETE_FAIL = 'FORMATION_DELETE_FAIL'

export const FORMATION_CREATE_REQUEST = 'FORMATION_CREATE_REQUEST'
export const FORMATION_CREATE_SUCCESS = 'FORMATION_CREATE_SUCCESS'
export const FORMATION_CREATE_FAIL = 'FORMATION_CREATE_FAIL'
export const FORMATION_CREATE_RESET = 'FORMATION_CREATE_RESET'

export const FORMATION_UPDATE_REQUEST = 'FORMATION_UPDATE_REQUEST'
export const FORMATION_UPDATE_SUCCESS = 'FORMATION_UPDATE_SUCCESS'
export const FORMATION_UPDATE_FAIL = 'FORMATION_UPDATE_FAIL'
export const FORMATION_UPDATE_RESET = 'FORMATION_UPDATE_RESET'
