export const PURCHASE_FORMATION_REQUEST = 'PURCHASE_FORMATION_REQUEST'
export const PURCHASE_FORMATION_SUCCESS = 'PURCHASE_FORMATION_SUCCESS'
export const PURCHASE_FORMATION_FAIL = 'PURCHASE_FORMATION_FAIL'
